version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - ${MONGODB_LOCAL_PORT}:27017
    volumes:
      - ${MONGODB_LOCAL_VOLUME}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    container_name: mongo

#  server:
#    build:
#      context: .
#      dockerfile: ./docker/server/Dockerfile
#    ports:
#      - ${SERVER_PORT}:${SERVER_PORT}
#    volumes:
#      - ./src:/usr/src/app/src
#      - ./.env:/usr/src/app/.env
#      - ./package.json:/usr/src/app/package.json
#      - ./package-lock.json:/usr/src/app/package-lock.json
#    stdin_open: true
#    tty: true
#    container_name: server
#
#  handler:
#    build:
#      context: .
#      dockerfile: ./docker/handler/Dockerfile
#    volumes:
#      - ./src:/usr/src/app/src
#      - ./.env:/usr/src/app/.env
#      - ./package.json:/usr/src/app/package.json
#      - ./package-lock.json:/usr/src/app/package-lock.json
#    stdin_open: true
#    tty: true
#    container_name: handler

networks:
  default:
    driver: bridge
    name: debezium_default
