declare const ElementEdge: {
  GRAPH_VISITORS_DEMOGRAPHIC: "GRAPH_VISITORS_DEMOGRAPHIC";
  GRAPH_VISITORS_STATISTICS: "GRAPH_VISITORS_STATISTICS";
  GRAPH_SHARES_STATISTICS: "GRAPH_SHARES_STATISTICS";
  GRAPH_FOLLOWERS_DEMOGRAPHIC: "GRAPH_FOLLOWERS_DEMOGRAPHIC";
  GRAPH_FOLLOWERS_STATISTICS: "GRAPH_FOLLOWERS_STATISTICS";
  TABLE_POSTS: "TABLE_POSTS";
};

export type ElementEdge = typeof ElementEdge[keyof typeof ElementEdge];
